### ISSUE TITLE
JOSS: Review on exaDEM docs

### ISSUE THREAD

**Issue by vsangelidakis** [Collab4exaNBody/exaDEM#100]
Hello, I share some suggestions to consider regarding your docs as part of my JOSS review. My comments look extensive but they are really small things that should not take more than a few minutes to implement.

1. Some optional suggestions, not requirements within this review, hoping they might help (@rprat-pro feel free to tick them when you have read them or optionally implemented them): 

- [x] In CONTRIBUTING.md, you state _“Please do not use the issue tracker for personal support requests (contact directly the authors [raphael.prat@cea.fr](mailto:raphael.prat@cea.fr)”_.  As the code grows, you might start receiving an unsustainably high amount of emails with questions of how to use the different features of the code. You could use the “Discussions” field in Github to keep track of personal support requests/advice of how to do something in the code, so that other users/devs can also benefit from the answer. In YADE, we keep a historical, open-source record of answers, and this is very helpful to us as devs and to the users who might have a question now that was answered already years ago.
- [x] Are you considering using the Sphinx LaTeΧ builder to create a pdf version of the documentation? This is also very handy for easy navigation of all docs in one place.
- [x] Section 5.3 Interaction / Contact - Contact model for polyhedra: Do you use GJK for contact detection and EPA for contact force calculations or something in-house? I suggest documenting how the contact point / contact normal / contact force are calculated for polyhedra, and if needed point to the relevant Rockable docs. 
- [x] Have you checked if your polyhedra conserve energy (always a tricky point for non-spherical particles in the DEM).
- [x] Section 7.1. Contact Force Laws - Regarding Contact Laws, you might want to look into more advanced contact models with time, such as Hertz-Mindlin (1949), Hertz-Mindlin and Deresiewicz (1953) and into more advanced viscous damping models, where the coefficient of restitution is velocity-dependent.
- [x] Section 8. Numerical Scheme - Regarding time integration, you might want to look into more advanced time integration schemes, such as SPIRAL (del Valle et al, Comput. Phys. Commun. 2024) for non-spherical particles. 

2. Some suggestions for improvement within this review:

- [x] The file CONTRIBUTING.md provides the very helpful `ctest --test-dir example` for unit tests, but IMO this should be added also in the docs, right after installation, so that a new/any user can quickly check the validity of their installation of exaDEM.
- [x] Do these tests only check that the script can start running, or is there any unit testing also based on results, e.g. compared to analytical/expected results?
- [x] To use exaDEM more easily, I found handy defining an alias in `~/.bashrc`, so that might be helpful advice for new users in the docs.
- [x] Example 3.1.1: The docs suggest two scripts for the rotating drum simulation (`/rotating-drum-full.msp` and `/rotating-no-periodic.msp`), but there are additional scripts in the folder (e.g. `/rotating-drum.msp`). I would suggest to either document all scripts or remove any redundant ones. This also happens in other examples, where only a few scripts are documented in the docs, and other variants of the scripts exist in the same folder, with no information of what why they are there - this can be confusing to a new user.
- [x] Regarding vtk outputs:
    - [x] #101
    - [x] You could also save stress tensors (static and/or dynamic) per particle, later on.
    - [x] I suggest documenting how the user can visualise the shape of polyhedra. I only see the points/positions in the vtp files.
    - [x] I suggest documenting how the user can visualise interparticle forces / force chains, if this is available.
    - [x] The output of all runs is saved in a folder “ExaDEMOutputDir”, and every run overwrites that files in that folder. For users running many examples from the same directory, it might be beneficial to add the choice to name the output folder in the input file, or show how to do this if this is already available.
- [x] With the exception of the first example, all other examples take a fairly long time to run / write vtk files, which could put off a new user. You could reduce the computation time by reducing the number of particles and/or modify the contact stiffness/density to accelerate these examples.
- [x] Examples 3.1.1 to 3.1.3, and 3.3.1: you use URLs as `exaDEM/examples/spheres/...`, but for Examples 3.1.4 to 3.2.5 you use truncated URLs as `examples/spheres/..`. This is a detail, but I would suggest using the same formatting across all cases.
- [x] Example 3.1.7: You should add the missing URL to the files.
- [x] Example 3.3.1: You are noting the old URL, as this example is now in `examples/spheres/cylinder_stl/cylinder_stl.msp`
- [x] Example 3.3.2: If this example is missing, I would suggest commenting it out, and add it when you are ready to release working example. This is a suggestion to help keep the docs clean.

Hope these comments help improve your already high-quality docs. Vasileios

**Comment by rprat-pro** [comment]
Thank you @vsangelidakis for your suggestions, they will indeed greatly improve the documentation. First, I'll try to answer and add your suggestions quickly (especially part 2). Then with @jmvanson and @lamarsid we'll think about improvements on the physics side. ExaDEM is still a young code that's flexible enough to integrate different contact modeling or time integration schemes so it's a good way to stress its design by trying new physiques =)

**Comment by vsangelidakis** [comment]
That's great @rprat-pro. Please do not overthink the answers to the points I raise, you can fix the few broken links/straightforward changes, and let me know so that I mark the review on JOSS as completed. 

You can keep my more open-ended suggestions as ideas for improvement outside of the review process (i.e. do not feel rushed to implement everything now).

**Comment by vsangelidakis** [comment]
One more thing: it would be helpful to report in the docs and in the JOSS paper if your spheropolyhedra have to be convex or if they can have any arbitrary shape.

**Comment by rprat-pro** [comment]
Yes, this approach enables us to handle non-convex shapes such as hexapods.

**Comment by vsangelidakis** [comment]
That's great - You should highlight that feature!

**Comment by rprat-pro** [comment]
Hi @vsangelidakis, here are some answers to your questions/tasks:

```
Are you considering using the Sphinx LaTeΧ builder to create a pdf version of the documentation? This is also very handy for easy navigation of all docs in one place.
```

We had added the commands to generate the pdf in the github `doc_exaDEM` but for the moment we hadn't planned to add a pdf as the site seemed sufficient. I think I'll add a documentation version to the next release if I can improve the rendering (which I think is pretty ugly).

```
    Section 5.3 Interaction / Contact - Contact model for polyhedra: Do you use GJK for contact detection and EPA for contact force calculations or something in-house? I suggest documenting how the contact point / contact normal / contact force are calculated for polyhedra, and if needed point to the relevant Rockable docs. 
```

@lamarsid :   GJK (Gilbert-Johnson-Keerthi) and EPA (Expanding Polytope Algorithm) are commonly used in DEM and can be implemented. However, we use an approach based on a spheropolyhedral representation  (with a Minkowski radius) of shapes, with detection relying on bounding boxes and cell-linking. In this approach, we identify four types of contacts: vertex-to-vertex, vertex-to-edge, edge-to-edge, and     vertex-to-face. The remaining types of contacts are combinations of these.

In addition, we're currently working with Vincent Richefeu (creator of Rockable) on a paper that explains all these aspects and will make a very good additional resource.

```
    Have you checked if your polyhedra conserve energy (always a tricky point for non-spherical particles in the DEM). 
```

@lamarsid :  Spheropolyhedra generate simultaneous multiple contacts (edge-edge and vertex-face at the same time for example), which can complicate the dynamics and potentially introduce energy losses if the forces are not calculated accurately. But as you say, event for other approaches it is a tricky point. 

```
    Section 7.1. Contact Force Laws - Regarding Contact Laws, you might want to look into more advanced contact models with time, such as Hertz-Mindlin (1949), Hertz-Mindlin and Deresiewicz (1953) and into more advanced viscous damping models, where the coefficient of restitution is velocity-dependent. 
```

@lamarsid :  For now, we are using linear viscoelastic contact laws, but nothing prevents us from using models such as Hertz-Mindlin. thank you for your advising.

```
    Section 8. Numerical Scheme - Regarding time integration, you might want to look into more advanced time integration schemes, such as SPIRAL (del Valle et al, Comput. Phys. Commun. 2024) for non-spherical particles. 
```


@lamarsid : exaDEM is a part of project for n-body interaction involing also molecular dynamics and SPH, for time integration, we use velocity Verlet witch is common scheme to these methods. for the future, we also want to add  Runge-Kutta and predictor-corrector. 
        
In addition,  ExaDEM makes it easy to change the integration scheme by modifying / adding operators in ``numerical_scheme: numerical_scheme_verlet`` with currently :

```
numerical_scheme_verlet: numerical_scheme_verlet_macro(compute_force)

numerical_scheme_verlet_macro(compute_force_op):
  name: scheme
  body:
#    - push_f_v_r: { dt_scale: 1.0 }
#    - push_f_v: { dt_scale: 0.5 }
#    - push_to_quaternion: { dt_scale: 1.0 }
    - combined_compute_prolog
    - push_av_to_quat_driver
    - push_v_to_r_driver
    - mpi_barrier
    - check_and_update_particles
    - reset_force_moment
    - mpi_barrier
    - compute_force_op
    - mpi_barrier
    - force_to_accel
#    - update_angular_acceleration 
#    - update_angular_velocity: { dt_scale: 1 }
#    - push_f_v: { dt_scale: 0.5 }
    - combined_compute_epilog
```

```
 Do these tests only check that the script can start running, or is there any unit testing also based on results, e.g. compared to analytical/expected results?
 ```
 
 Indeed, we don't test that the physical results remain exactly the same. We had initially planned to compare particle positions, but this turned out to be more complicated than expected, as depending on the hardware architecture, compiler and type of parallelization, we didn't obtain exactly the same result. We had thought of adding a relative tolerance, but finally we moved on to other problems... On the other hand, as soon as the code starts to go wrong, we generally miss a contact and the code crashes very quickly with an error or calculation times increase enormously. In the end, it's still an open question, perhaps by adding post-processing ...  

```
 You could also save stress tensors (static and/or dynamic) per particle, later on.
 ```
 
 Issue #44 . Yes, it's planned, it's just a question of time and priority.
 
 For other points:
 
 - I added the operator `io_config:` to the examples to specify the output directory,
 - I've renamed the examples so that the minimal cases contain “mini” in their names,
 - I've added some time slots to give the reader an idea of the simulations before running them,
 - I've provided a few links to post-processing with Paraview at the beginning of the Test cases section,
 - Two examples propose to display the contact network,
 - This example is "ready" 3.3.2 but I need to write the description in the following days with the input files.
 
![pale-huge-slide](https://github.com/user-attachments/assets/5a38d8fd-355b-4cf4-84ac-9ab9a4e5344e)
![pale-huge-profile](https://github.com/user-attachments/assets/bdf9e9de-d7db-4ca4-91c6-23a7e7953a7e)


I hope I've answered all your questions. 
Thanks again for your great comments.

**Comment by vsangelidakis** [comment]
Thank you for the detailed answers - Happy to approve the review at JOSS.

Regarding regression tests and checks to verify physical results, I would suggest implementing these sooner rather than later, to make sure that every new commit does not break the reproducibility of your code. There are a few available two-particle problems with analytical solutions (e.g. see Chung and Ooi, 2011, Granul. Matter), as well as bulk-scale benchmarks you can look at. For these you might want to introduce a tolerance as you say, as indeed parallelisation and system architecture can influence the sequence of operations and induce small differences that do not allow for perfectly deterministic results.

Well done writing this code and releasing it in an open-source manner.

All the best,
Vasileios

**Comment by rprat-pro** [comment]
Thank you again for your review. 

I've just had a look at the article “Benchmark tests for verifying discrete element modelling codes at particle impact level” and it seems easy enough to add it for spherical particles. Thank you.
